#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.
# Docs: https://gohugo.io/content-management/menus/#define-in-site-configuration

main:
  - identifier: courses
    name: WHAT WE DO
    weight: 1
  - parent: courses
    name: HOUSE
    url: /what-we-do
    weight: 1
  - parent: courses
    name: KIDS CLUB
    url: /what-we-do
    weight: 2
  - parent: courses
    name: HOPE GARDEN
    url: /what-we-do
    weight: 3
  - parent: courses
    name: WOMEN'S YOGA
    url: /what-we-do
    weight: 4
  - identifier: practice
    name: HOW I CAN HELP
    weight: 2
  - parent: practice
    name: PRAYING
    url: /how-you-can-help/
    weight: 1
  - parent: practice
    name: VOLUNTEERING
    url: /how-you-can-help/
    weight: 2
  - parent: practice
    name: PROVIDING SERVICE
    url: /how-you-can-help/
    weight: 3
  - parent: practice
    name: DONATING
    url: /how-you-can-help/
    weight: 4
  - identifier: about
    name: ABOUT
    weight: 3
  - parent: about
    name: HISTORY
    url: /about/
    weight: 1
  - parent: about
    name: OUR TEAM
    url: /people
    weight: 2
  - parent: about
    name: MINISTRY
    url: /about
    weight: 3
  - parent: about
    name: OUTREACH
    url: /about
    weight: 4
  - identifier: site
    name: CONTACT
    weight: 4
  - parent: site
    name: CONTACT US
    url: /contact
    weight: 1
  - parent: site
    name: SUBSCRIBE
    url: /subscribe
    weight: 2
  - parent: site
    name: RSS
    url: /index.xml
    weight: 3
  - parent: site
    name: LINKS
    url: /links
    weight: 4
  - parent: site
    name: FREE RESOURCE
    url: /Free
    weight: 5

footer:
  - identifier: about
    name: ABOUT
    weight: 1
  - parent: about
    name: History
    url: /about/
    weight: 1
  - parent: about
    name: People
    url: /people
    weight: 2
  - parent: about
    name: Ministry
    url: /about
    weight: 3
  - parent: about
    name: Outreach
    url: /about
    weight: 4
  - identifier: courses
    name: What We Do
    weight: 2
  - parent: courses
    name: House
    url: /what-we-do
    weight: 1
  - parent: courses
    name: Kids Club
    url: /what-we-do
    weight: 2
  - parent: courses
    name: Hope Garden
    url: /what-we-do
    weight: 3
  - parent: courses
    name: Women's Yoga
    url: /what-we-do
    weight: 4
  - identifier: practice
    name: How I Can Help
    weight: 3
  - parent: practice
    name: Praying
    url: /how-you-can-help/
    weight: 1
  - parent: practice
    name: Volunteering
    url: /how-you-can-help/
    weight: 2
  - parent: practice
    name: Providing Service
    url: /how-you-can-help/
    weight: 3
  - parent: practice
    name: Donating
    url: /how-you-can-help/
    weight: 4
  - identifier: site
    name: SITE
    weight: 4
  - parent: site
    name: RSS
    url: /index.xml
    weight: 1
  - parent: site
    name: Contact
    url: /contact
    weight: 2
  - parent: site
    name: Subscriber
    url: /subscribe
    weight: 3
  - parent: site
    name: Links
    url: /links
    weight: 4
  - parent: site
    name: Free Resource
    url: /Free
    weight: 5
 