# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: red

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'The highly-customizable Hugo Academic theme powered by Hugo Blox Builder. Easily create your personal academic website.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Announcement shown above the header
announcement:
  enable: true
  text: "🚀 New pre-print available – read it now!"
  url:  "/publication/pre-print/"
  
# Tailwind: allow @apply inside <style> tags (needed once per site)
tailwind:
  compile_inline_css: true

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    button:
      enable: true
      text: "Donate"
    fixed_to_top: false
    show_search: true
    show_theme_chooser: true
    logo:
     # Logo filename in `assets/media/` folder
      text: "Your Name"

# Site footer
footer:
  content:
    logo:
      text: HeLLO 
    subtitle: HAVE WE ARRIVED YET?
    tagline: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.
    subscribe: or not
  design:
    columns: 4
  copyright:
    notice: '© {year} User. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false
  show_translations: true

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: true
extensions:
  academicons:
    enable: true

features:
  icons:
    enable: true

page:
  toc: true

toc: true