# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: red

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'The highly-customizable Hugo Academic theme powered by Hugo Blox Builder. Easily create your personal academic website.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Announcement shown above the header
announcement:
  enable: true
  text: "☕ A Cuppa And a Chat"
  url: "/publication/pre-print/"
  phone: "+1234567890"
  email: "contact@example.com"
  hours: "mon 9am-6pm"
  hours: "tue 9am-6pm"    # 9-hour meeting
  hours: "wed 8am-5pm"  # 9-hour meeting  
  hours: "thur 9am-12pm" # 3-hour meeting
  hours: "fri 10am-2pm" # 4-hour meeting
  address: "123 Main Street, Your City, State 12345"
  latitude: "40.7128"
  longitude: "-74.0060"
  meeting_title: "Business Meeting"
  preferred_meeting_hour: 11  # Optional: Choose specific hour (9-17), defaults to opening hour

  
# Tailwind: allow @apply inside <style> tags (needed once per site)
tailwind:
  compile_inline_css: true

# Site header
header:
  navbar:
    enable: true
    blox: "navbar1"
    button:
      enable: true
      text: "Donate"
      url: /donate
    fixed_to_top: false
    show_search: true
    show_theme_chooser: true
    logo:
     # Logo filename in `assets/media/` folder
      text: "Your Name"

# Site footer
footer:
  content:
    logo:
      text: ASUMET CHARITY
      image: "" # static/images
    subtitle: 
    tagline: We are Extending Christ’s love to those marginalized by age, ethnicity, disability, or destitution. We are registered charity No 1234567 and Uk registered company limited No 238753 based in west london
    tagline_images:
       - "/images/li-yang-5h_dMuX_7RE-unsplash.webp" # static/images multiple images one under other
    tagline_images_alt:
       - "Partner 1 Logo"
    subscribe: or not
  design:
    columns: 3
  copyright:
    notice: '© {year} User. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: false
  show_translations: true

links_above_social:

social:
  - icon: 'brands/twitter'
    icon_pack: 'fab'
    name: 'Twitter'
    link: 'https://twitter.com/yourusername'
  - icon: 'brands/facebook'
    icon_pack: 'fab' 
    name: 'Facebook'
    link: 'https://facebook.com/yourpage'
  - icon: 'brands/linkedin'
    icon_pack: 'fab'
    name: 'LinkedIn'
    link: 'https://linkedin.com/in/yourprofile'
  - icon: 'brands/instagram'
    icon_pack: 'fab'
    name: 'Instagram'
    link: 'https://instagram.com/yourusername'
links_below_social:
  - name: "Sitemap"
    url: "/sitemap.xml"
  - name: "RSS Feed"
    url: "/index.xml"
  - name: "API Docs"
    url: "/api"
social_text: "Connect with us on social media! Follow us for updates, news, and exclusive content."

fundraising:
  stewardship_api_key: "your-api-key"
  bank_api_key: "your-bank-key"
  update_interval: 30000  # 30 seconds
  demo_mode: true  # Set to false for production

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: true
extensions:
  academicons:
    enable: true

features:
  icons:
    enable: true

toc: true